---
- hosts: production
  become: true
  tasks:
    - name: Install apcahe
      apt: name=apache2 state=present update_cache=yes

- hosts: jenkins
  become: true
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=yes

